### ISSUE TITLE
SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by lojanet** [Odoo-EC/l10n-ecuador#20]
Module
l10n_ec_account_edi

Describe the bug
SyntaxError: unexpected EOF while parsing

To Reproduce
Affected versions:
V15

1. Install module l10n_ec_account_edi
2. Show Full Accounting Feactures
3. In Accounting Dashboard Open any Invoice
![18329384-d3d6-4209-b338-7b6ce43e75bd](https://github.com/Odoo-EC/l10n-ecuador/assets/37152209/cb38d201-80cf-4c9a-bc08-50995b05b51b)

**Comment by celm1990** [comment]
corregido en https://github.com/Odoo-EC/l10n-ecuador/pull/21
