### ISSUE TITLE
Novedades en autorización sri 

### ISSUE THREAD

**Issue by yazber** [Odoo-EC/l10n-ecuador#9]
Se puede visualizar un error de autorización cuando el ws del SRI no se encuentra operativo, esto implica el no tener un estado en la respuesta para ser evaluado mil disculpas la imagen no pude obtener por completo el mensaje pero nos podría dar una idea, para poder controlar 

![Captura desde 2023-04-19 00-23-24](https://user-images.githubusercontent.com/3648230/232974786-826629b9-c7e1-4dc8-8d86-10dc3e35cdda.png)

**Comment by celm1990** [comment]
Esto fue corregido en el commit 
https://github.com/Odoo-EC/l10n-ecuador/commit/b25c79af30ddc136c2a664b0d5ae4f55e7408049#diff-6bcb670591ed0409660f91774b4ae6a05e4311cc198b0b3f262dc5e30bbbda85L519
